### PR TITLE
[doc] add adopt a commit doc from a mailling list answer

### PR DESCRIPTION
**Pull request by hogoww**
from @tesonep

### CODE REVIEW

**Comment by tinchodias** [comment]
Is this a Work in Progress? Should it be merged like this?

**Comment by hogoww** [comment]
There was a mail on the Pharo mailing list

**Comment by hogoww** [comment]
This is as far as I'll go.

There was a explanatory mail on the Pharo mailing list iirc, and I thought it could be good to have a documentation even partial for something undocumented (at the time).

**Comment by tinchodias** [comment]
Thanks

**Pull request merged**
