### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by crunsk**
Changed 'atttached' to 'attached'.

### CODE REVIEW

**Comment by astares** [comment]
Note this is against "dev-1.0" branch instead of "dev-1.6".

**Comment by crunsk** [comment]
> 
> 
> Note this PR is against "dev-1.0" branch instead of "dev-1.6".

Should I do this change against the branch  "dev-1.6" and then do a pull request?

**Comment by guillep** [comment]
> Should I do this change against the branch "dev-1.6" and then do a pull request?

I've just tried to make the pull request target branch dev-1.6, but it came with lots of noise... I don't think github is smart enough to make this merge...

So, yes, could you do it against 1.6? It could be merged right away.

Thanks BTW!

**Comment by crunsk** [comment]
Ok, [here's a link](https://github.com/pharo-vcs/iceberg/pull/1371) to the new pull request. Hopefully that's ok. :)

**Comment by guillep** [comment]
We can close this one now.

Thanks again!

**Pull request closed without merging**
