### PR TITLE
Fogbugz panel: Improve label, focus order and layout

### PR DESCRIPTION
**Pull request by jecisc**
- Rename label from FogBugz issue to Pharo issue Number
- The focus order now works right
- Redefine the extent of the window

Fixes https://github.com/pharo-vcs/iceberg/issues/739

### CODE REVIEW

**Comment by jecisc** [comment]
I extracted the duplicated parts

**Comment by guillep** [comment]
Tx @jecisc :)

**Comment by astares** [comment]
Thanks!

**Comment by guillep** [comment]
In the latest version the focus is not working... At least I cannot see it because Tab does not change focus at all when the focus is on the list on the left.

**Pull request merged**
