### PR TITLE
Move wiki files to a docs directory (so we can accept pull requests) …

### PR DESCRIPTION
**Pull request by macta**
…along with some minor grammatical changes and a new entry for recovering code.

As suggested by Esteban to move away from the wiki.

### CODE REVIEW

**Comment by cdlm** [comment]
Still, the wiki is nice to browse on github. I think github wikis have their own git repo, but I should check if that's still the case. If it is, then the wiki content could be managed as a branch of the main repo; we'd have to synchronize it ourselves I guess, but then people could browse it online…

**Comment by macta** [comment]
This is the annoying thing - it’s a second class repo so you can’t fork and PR - wasted hours on it already and found lots of similar complaints - it’s totally stupid.

**Comment by cdlm** [comment]
What I mean is, you could have a branch in the 1st class repo that contains the same thing as the 2nd class one. I believe that would allow PRs, and synchronizing with the wiki repo would be normal push/pull, we just have to remember to do it.

Alternate solution: use `git subrepo` to synchronize the `docs/` directory with the wiki repo.

**Comment by macta** [comment]
Damien - that looks interesting, I’ll give it a shot. Still don’t understand why github made this all so complicated in the first place (why did it even need to be a separate repo for a wiki) - what a disaster.

**Comment by guillep** [comment]
The automatic upgrade could be done on the CI.

Let's integrate this, and work on the other solution afterwards.

**Pull request merged**
