### PR TITLE
[IGNORE] Adaptaion to Commander classes renames

### PR DESCRIPTION
**Pull request by dionisiydk**
Command word is omitted in common activation strategies:
- CmdShortcutActivation instead of CmdShortcutCommandActivation
- CmdContextMenuActivation instead of CmdContextMenuCommandActivation 
- CmdDragAndDropActivation instead of CmdDragAndDropCommandActivation
- ClyToolbarActivation instead of ClyToolbarCommandActivation

Now old names are available as deprecated classes. Deprecation ensures that users will receive new class instances.

Without this pull request you should be able to aply deprecation in image from context menu of deprecated class (when Calypso 0.11.5 wil be integrated)

### CODE REVIEW

**Comment by guillep** [comment]
Hi @dionisiydk, the PR does not merge. Could you fix it please? Thanks

**Comment by dionisiydk** [comment]
Done. Thanks for remind. I forgot to look at status.

But I have problem with Calypso integration with these changes. Pharo PR does not update Commander correctly.
Maybe it's better to first update Commander version without real code changes.
I will prepare another PR. But do not close this one.

**Comment by jecisc** [comment]
Is it right to have this PR agains dev-0.7 and not 1.0?

**Comment by dionisiydk** [comment]
it should be 1.0. But I don't found dev for 1.0.  Is it exist?

**Comment by guillep** [comment]
Nope, it should be dev-1.0, I've just updated it.

**Comment by dionisiydk** [comment]
Yes, I don't notice dev-1.0 (forgot to fetch)

**Comment by dionisiydk** [comment]
I made another PR https://github.com/pharo-vcs/iceberg/pull/846.
It can be merged and integrated with current Calypso version.

**Comment by guillep** [comment]
I don't understand, should I close this one then?

**Pull request closed without merging**
