### PR TITLE
issue1004-displayScaleFactor

### LINKED ISSUE #1004: use displayScaleFactor
The Iceberg UI should use displayScaleFactor to work better on HiDPI displays or during presentations

### PR DESCRIPTION
**Pull request by pavel-krivanek**
use displayScaleFactor for hardcoded dimensions
Fixes #1004

### CODE REVIEW

**Comment by guillep** [comment]
Wow we need new icons :)

**Comment by estebanlm** [comment]
> Wow we need new icons :)
in fact I'm exploring the possibility of using .icns icons instead .png (to have different sizes to choose).

**Comment by estebanlm** [comment]
btw, @pavel-krivanek If you just call your branch NUMBER-name (without the issue prefix), waffle will do some movements automatically and we will all be happier :P

**Comment by pavel-krivanek** [comment]
only some failing tests like: IceGenericError: curl error: Could not resolve host: github.com

**Pull request merged**
