### PR TITLE
issue329

### PR DESCRIPTION
**Pull request by pavel-krivanek**

### CODE REVIEW

**Comment by jecisc** [comment]
I get this issue *a lot*. I would be cool if it could be integrated.

**Comment by cdlm** [comment]
Drive-by remark unrelated to this precise issue: I'm pretty sure github can upgrade issues to pull requests provided the PR is done properly (should check the API… but `hub` can do it). This would avoid splitting discussion on two threads with no link besides a title that requires switching context and searching to find what this PR is about =_=

**Comment by j4yk** [comment]
Not sure about upgrading, but you can mention the issue with #329. If you include "closes #329" or "fixes #329" in commit messages or pull request texts, the issue will be closed automatically, when the commit or PR is merged into master.

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by cdlm** [comment]
@j4yk yes, mentioning the issue in one of the PR commit messages would help too. This is what I meant (from the help of https://hub.github.com):

```
$ hub help pull-request
usage: git pull-request [-f] [-m <MESSAGE>|-F <FILE>|-i <ISSUE>|<ISSUE-URL>] [-o] [-b <BASE>] [-h <HEAD>]
```

> Opens a pull request on GitHub for the project that the "origin" remote
points to.
> *[…]*
> **If instead of normal <TITLE> an issue number is given with "-i", the pull
request will be attached to an existing GitHub issue. Alternatively, instead
of title you can paste a full URL to an issue on GitHub.**

**Pull request merged**
